f=open("f:/abc.txt","rt")
str=f.read(10)
print("read string is:",str)
position=f.tell()
print("current file position:",position)
position=f.seek(0,0)
str=f.read(10)
print("again read string is:",str)
f.close()
